name: Deploy Wasm to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Production
        run: ./gradlew :composeApp:jsBrowserDistribution

      - name: Remove .map files
        run: rm -f composeApp/build/dist/wasmJs/productionExecutable/*.map

      - name: Create .nojekyll
        run: touch composeApp/build/dist/js/productionExecutable/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: composeApp/build/dist/wasmJs/productionExecutable
          branch: gh-pages